#!/usr/bin/env bash

set -e

set -vx
(cd charts/kube-node-init; helm package .)
chart-releaser upload -o mumoshu -r kube-node-init -t $GITHUB_TOKEN -p charts/kube-node-init
chart-releaser index -o mumoshu -r kube-node-init -t $GITHUB_TOKEN -p docs/index.yaml
